export type SpendKey = "dining" | "grocery" | "gas" | "travel" | "other";

export interface CardDef {
  id: string;
  name: string;
  issuer: string;
  annualFee: number;
  rates: Record<SpendKey, number>;
  badge: string;
  color: string;
  description: string;
  img: string;
  bankUrl: string;
  perks: string[];
}

export interface Step {
  key: SpendKey;
  icon: string;
  label: string;
  question: string;
  hint: string;
  max: number;
  defaultVal: number;
  presets: { label: string; value: number }[];
}

export const DEFAULT_SPEND: Record<SpendKey, number> = {
  dining: 400, grocery: 600, gas: 150, travel: 300, other: 500,
};

export const CAT_LABELS: Record<SpendKey, string> = {
  dining: "Dining", grocery: "Groceries", gas: "Gas", travel: "Travel", other: "Shopping",
};

export const CARDS: CardDef[] = [
  {
    id: "cobalt",
    name: "Amex Cobalt",
    issuer: "American Express",
    annualFee: 191.88,
    rates: { dining: 0.05, grocery: 0.05, gas: 0.02, travel: 0.02, other: 0.01 },
    badge: "🍽️ Best for Dining",
    color: "var(--accent-rose)",
    description: "5x points on dining & groceries. Massive welcome bonus. Best for food spenders.",
    img: "/cards/amex-cobalt.webp",
    bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/cobalt-card/",
    perks: ["5x on dining & food delivery", "5x on groceries", "2x on travel & transit", "1x everything else", "$15.99/month ($191.88/yr · $191.88/yr in Quebec)"],
  },
  {
    id: "scotia-gold",
    name: "Scotia Gold Amex",
    issuer: "Scotiabank",
    annualFee: 120,
    rates: { dining: 0.05, grocery: 0.06, gas: 0.03, travel: 0.01, other: 0.01 },
    badge: "🛒 Best Grocery Card",
    color: "var(--accent-warm)",
    description: "6x Scene+ at Sobeys, Safeway & more. 5x on dining, food delivery & entertainment. 3x on gas, transit & streaming.",
    img: "/cards/Scotiabank-gold-amex.avif",
    bankUrl: "https://hello.scotiabank.com/lending/triage?productCode=AXG&subProductCode=GC&source=116B&language=en",
    perks: ["6x Scene+ at Sobeys, Safeway, FreshCo, Foodland & more", "5x on dining, food delivery, food subscriptions & other grocery", "5x on eligible entertainment (movies, theatre, tickets)", "3x on gas, transit, rideshare & streaming services", "Up to 4x on hotels & car rentals via Scene+ Travel · 1x all other travel · $120/yr annual fee"],
  },
  {
    id: "td-aeroplan",
    name: "TD Aeroplan Visa Infinite",
    issuer: "TD Bank",
    annualFee: 139,
    rates: { dining: 0.01, grocery: 0.015, gas: 0.015, travel: 0.015, other: 0.01 },
    badge: "✈️ Best Travel",
    color: "#6B8FC9",
    description: "1.5x Aeroplan on gas, EV charging, groceries & Air Canada. 1x on everything else.",
    img: "/cards/td-aeroplan-infinite.png",
    bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/aeroplan/",
    perks: ["1.5x Aeroplan Points on gas, EV charging, groceries & Air Canada purchases", "1x Aeroplan Point on all other purchases", "Earn points twice at 150+ Aeroplan partners & 200+ online retailers via Aeroplan eStore", "Comprehensive travel insurance", "$139/yr annual fee"],
  },
  {
    id: "rbc-avion",
    name: "RBC Avion Visa Infinite",
    issuer: "RBC",
    annualFee: 120,
    rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.0125, other: 0.01 },
    badge: "🔄 Most Flexible",
    color: "#4A90D9",
    description: "1.25x Avion points on travel. 1x on all other purchases. Transfer to 30+ airline partners.",
    img: "/cards/rbc-avion-infinite.webp",
    bankUrl: "https://apps.royalbank.com/apps/IAO/apply/cardapp?pid1=avion_inf&ASC=3D2111&_gl=1*1jecaqy*_gcl_au*MzQ5OTM5MDc2LjE3NzgzNzQ5MjI.*_ga*MjEwMDcyNDEyNC4xNzc4Mzc0OTIy*_ga_89NPCTDXQR*czE3NzgzNzQ5MjEkbzEkZzEkdDE3NzgzNzQ5NDgkajMzJGwwJGgw",
    perks: ["1.25x Avion Points on travel-related purchases", "1x Avion Point on all other eligible purchases", "Transfer to 30+ airline partners", "Travel insurance included", "$120/yr annual fee"],
  },
  {
    id: "bmo-eclipse",
    name: "BMO Eclipse Visa Infinite",
    issuer: "BMO",
    annualFee: 120,
    rates: { dining: 0.0333, grocery: 0.0333, gas: 0.0333, travel: 0.0067, other: 0.0067 },
    badge: "⛽ Best Gas Card",
    color: "#2B6CB0",
    description: "5x BMO Rewards points per $1 on groceries, gas, transit & dining. 1x on everything else.",
    img: "/cards/bmo-eclipse.png",
    bankUrl: "https://www.bmo.com/main/personal/credit-cards/getting-started/?lang=en&rg=BMO&PID=VISDX&MID=3930192&OFFERCODE=RQTSX00008&OFFERDATE=20251031&income_quiz=true&income=60000&household_income=100000&monthly_spend=1250&PIDBASE=VPVDM&PIDUP=VISDY&MIDBASE=3930758&OFFERCODEBASE=RQTVP00001&OFFERDATEBASE=20220910&MIDUP=6011141&OFFERCODEUP=RQTSY00005&OFFERDATEUP=20251031&income_up=150000&household_income_up=200000&monthly_spend_up=4167",
    perks: ["5x BMO Rewards points per $1 on groceries", "5x per $1 on gas, public transit & rideshare", "5x per $1 on dining, takeout & food delivery", "1x BMO Rewards point per $1 on all other purchases", "$50 annual lifestyle credit · $120/yr annual fee"],
  },
  {
    id: "wealthsimple",
    name: "Wealthsimple Card",
    issuer: "Wealthsimple",
    annualFee: 0,
    rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.02, other: 0.02 },
    badge: "💸 2% Everything",
    color: "#48BB78",
    description: "2% cashback on everything. No FX fees. Earn up to 2.25% interest on cashback. Fee waived with $100K+ or qualifying paycheque deposit.",
    img: "/cards/newwealthsimple.webp",
    bankUrl: "https://www.wealthsimple.com/en-ca/spend",
    perks: ["2% cashback on all purchases", "0% foreign transaction fees (save up to $177/yr)", "Monthly fee waived with $100K+ in assets or a qualifying paycheque deposit", "Earn up to 2.25% interest on your cashback", "No virtual card tap limit"],
  },

  // ── AMERICAN EXPRESS ──────────────────────────────────────
  { id: "amex-gold", name: "Amex Gold Rewards", issuer: "American Express", annualFee: 250, rates: { dining: 0.01, grocery: 0.02, gas: 0.02, travel: 0.02, other: 0.01 }, badge: "✈️ Travel Rewards", color: "#D4AF37", description: "2x on travel & dining. Flexible Membership Rewards. Good for travel spenders.", img: "/cards/amex-gold.avif", bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/gold-rewards-card/", perks: ["2x points on travel & dining", "1x on everything else", "Airport lounge access", "Travel insurance included", "$250/yr annual fee"] },
  { id: "amex-platinum", name: "Amex Platinum Card", issuer: "American Express", annualFee: 799, rates: { dining: 0.02, grocery: 0.01, gas: 0.01, travel: 0.02, other: 0.01 }, badge: "💎 Ultra Premium", color: "#C0C0C0", description: "Premium travel card with unlimited lounge access and top-tier insurance.", img: "/cards/amex-platinum.avif", bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/the-platinum-card/", perks: ["3x on travel & dining", "Unlimited airport lounge access", "$200 annual travel credit", "Premium concierge service", "$799/yr annual fee"] },
  { id: "amex-simply-cash-preferred", name: "Amex SimplyCash Preferred", issuer: "American Express", annualFee: 119.88, rates: { dining: 0.02, grocery: 0.04, gas: 0.04, travel: 0.02, other: 0.0125 }, badge: "⛽ Gas Cashback", color: "#2D5A27", description: "4% cashback on gas & groceries. 1.25% on everything else. Best flat-rate cashback Amex.", img: "/cards/amex-simply-cash-preferred.avif", bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/simplycash-preferred-card/", perks: ["4% cashback on gas", "4% cashback on groceries", "1.25% on all other purchases", "Purchase protection", "$9.99/month ($119.88/yr · $119/yr in Quebec)"] },
  { id: "amex-simply-cash", name: "Amex SimplyCash", issuer: "American Express", annualFee: 0, rates: { dining: 0.0125, grocery: 0.02, gas: 0.02, travel: 0.0125, other: 0.0125 }, badge: "💸 No-Fee Cashback", color: "#2D5A27", description: "2% on gas & groceries (grocery capped at $300/yr cashback). 1.25% on everything else including dining.", img: "/cards/amex-simply-cash.webp", bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/simplycash-card/", perks: ["2% cashback on gas", "2% cashback on groceries (max $300/yr)", "1.25% on everything else including dining", "No annual fee", "Purchase protection"] },
  { id: "amex-marriott", name: "Amex Marriott Bonvoy", issuer: "American Express", annualFee: 150, rates: { dining: 0.03, grocery: 0.02, gas: 0.03, travel: 0.05, other: 0.02 }, badge: "🏨 Hotel Points", color: "#8B0000", description: "5x points at Marriott hotels. 3x on gas, dining & travel. 2x on everything else.", img: "/cards/amex-marriott.avif", bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/marriott-bonvoy-american-express/", perks: ["5x Bonvoy points at participating Marriott hotels", "3x points on gas, dining & travel", "2x points on everything else", "Annual free night certificate", "$150/yr annual fee"] },
  { id: "amex-business-edge", name: "Amex Business Edge", issuer: "American Express", annualFee: 99, rates: { dining: 0.03, grocery: 0.03, gas: 0.03, travel: 0.01, other: 0.01 }, badge: "💼 Business Card", color: "#1a3a5c", description: "3x on business essentials: dining, grocery, gas. Great for small business owners.", img: "/cards/amex-business-edge.avif", bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/business-edge-card/", perks: ["3x on dining, groceries & gas", "1x on all other purchases", "Employee cards available", "Business insights dashboard", "$99/yr annual fee"] },
  { id: "amex-aeroplan", name: "Amex Aeroplan Reserve", issuer: "American Express", annualFee: 599, rates: { dining: 0.02, grocery: 0.0125, gas: 0.0125, travel: 0.03, other: 0.0125 }, badge: "✈️ Aeroplan Elite", color: "#003366", description: "3x Aeroplan on Air Canada. 2x on dining & food delivery. 1.25x on everything else.", img: "/cards/amex-aeroplan.avif", bankUrl: "https://www.americanexpress.com/en-ca/credit-cards/aeroplan-reserve-card/", perks: ["3x Aeroplan points on Air Canada & Air Canada Vacations", "2x Aeroplan points on dining & food delivery in Canada", "1.25x points on everything else", "Priority boarding & check-in", "$599/yr annual fee"] },

  // ── SCOTIABANK ────────────────────────────────────────────
  { id: "scotia-passport", name: "Scotia Passport Visa Infinite", issuer: "Scotiabank", annualFee: 150, rates: { dining: 0.02, grocery: 0.03, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "🌍 No FX Fees", color: "#CC0000", description: "3x Scene+ at Sobeys & participating grocers. 2x on dining, entertainment & transit. 1x everything else. No FX fees.", img: "/cards/scotia-passport.webp", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/passport-infinite-card.html", perks: ["3x Scene+ at Sobeys, Safeway, Foodland, IGA & co-ops", "2x on dining & other eligible grocery stores", "2x on entertainment (movies, theatre, tickets)", "2x on transit (rideshare, buses, taxis, subways) · Up to 4x hotels & car rentals via Scene+ Travel · 1x all other travel", "No foreign transaction fees · $150/yr annual fee"] },
  { id: "scotia-passport-privilege", name: "Scotia Passport Visa Infinite Privilege", issuer: "Scotiabank", annualFee: 599, rates: { dining: 0.02, grocery: 0.01, gas: 0.01, travel: 0.03, other: 0.01 }, badge: "✈️ Premium Travel", color: "#CC0000", description: "3x Scene+ on travel. Up to 6x on hotels & car rentals via Scene+ Travel. 2x on dining & entertainment.", img: "/cards/scotia-passport-privilege.avif", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/passport-visa-infinite-privilege-card.html", perks: ["3x Scene+ on eligible travel purchases", "Up to 6x on hotels & car rentals via Scene+ Travel (3x base + 3x extra)", "2x on eligible dining & entertainment", "1x on all other eligible purchases", "$599/yr annual fee"] },
  { id: "scotia-momentum-infinite", name: "Scotia Momentum Visa Infinite", issuer: "Scotiabank", annualFee: 120, rates: { dining: 0.02, grocery: 0.04, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "💵 Cashback King", color: "#CC0000", description: "4% cashback on groceries & recurring bills. 2% on gas, transit & food delivery. 1% on everything else.", img: "/cards/scotia-momentum-infinite.webp", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/momentum-infinite-card.html", perks: ["4% cashback on groceries & recurring payments (bills & subscriptions)", "2% on gas, EV charging, transit, rideshares & food delivery", "1% on all other purchases including restaurant dining & travel", "4% & 2% rates apply on first $25,000 in annual spend · 1% after", "$120/yr annual fee"] },
  { id: "scotia-momentum", name: "Scotia Momentum Visa", issuer: "Scotiabank", annualFee: 49, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "💵 Everyday Cashback", color: "#CC0000", description: "2% on groceries, food delivery, drugstores, gas, transit & recurring bills. 1% on everything else.", img: "/cards/scotia_momentum_visa.avif", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/momentum-no-fee-card.html", perks: ["2% cashback on groceries, food delivery & food subscriptions", "2% on drugstore purchases", "2% on gas, EV charging, transit & rideshares", "2% on recurring bills & eligible streaming subscriptions", "$49/yr annual fee · 1% on all other purchases"] },
  { id: "scotia-momentum-student", name: "Scotia Momentum Visa for Students", issuer: "Scotiabank", annualFee: 49, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "🎓 Student Cashback", color: "#CC0000", description: "Same 2% cashback as the Momentum Visa. Designed for students.", img: "/cards/scotia_momentum_visa.avif", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/momentum-no-fee-card.html", perks: ["2% cashback on groceries, food delivery & food subscriptions", "2% on drugstore purchases", "2% on gas, EV charging, transit & rideshares", "2% on recurring bills & eligible streaming subscriptions", "$49/yr annual fee · 1% on all other purchases"] },
  { id: "scene-plus-visa", name: "Scene+ Visa", issuer: "Scotiabank", annualFee: 0, rates: { dining: 0.01, grocery: 0.02, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "🎬 Scene+ Points", color: "#CC0000", description: "2x Scene+ at Sobeys, Safeway & partner grocers. 2x at Cineplex & Home Hardware. Up to 4x on hotels via Scene+ Travel.", img: "/cards/scene-plus-visa.webp", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/scene-card.html", perks: ["2x Scene+ at Sobeys, Safeway, Foodland, IGA & co-ops", "2x at Cineplex theatres & cineplex.com", "2x at Home Hardware, Home Building Centre & Home Furniture in Canada", "Up to 4x on hotels & car rentals via Scene+ Travel · 1x all other travel", "No annual fee · 1x on everything else"] },
  { id: "scotiabank-amex", name: "Scotiabank American Express Card", issuer: "Scotiabank", annualFee: 0, rates: { dining: 0.02, grocery: 0.03, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "🆓 No-Fee Amex", color: "#CC0000", description: "3x Scene+ at Sobeys & major grocers. 2x on dining, food delivery, entertainment, gas & streaming. No annual fee.", img: "/cards/scotibank_amex_red.png", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/american-express.html", perks: ["3x Scene+ at Sobeys, Safeway, FreshCo, Foodland & more", "2x on dining, food delivery, food subscriptions & other eligible grocery", "2x on entertainment (movies, theatre, tickets)", "2x on gas, transit, rideshares & eligible streaming services", "Up to 4x on hotels & car rentals via Scene+ Travel · 1x all other travel · No annual fee"] },
  { id: "scotia-platinum", name: "Scotiabank Platinum Amex", issuer: "Scotiabank", annualFee: 399, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.02, other: 0.02 }, badge: "💳 Flat-Rate Premium", color: "#CC0000", description: "2x Scene+ on all eligible purchases. Up to 5x on hotels & car rentals via Scene+ Travel. Unlimited lounge access.", img: "/cards/scotia-platinum.webp", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/american-express/platinum-card.html", perks: ["2x Scene+ on all eligible purchases", "Up to 5x on hotels & car rentals via Scene+ Travel (2x base + 3x extra)", "Unlimited airport lounge access", "No foreign transaction fees", "$399/yr annual fee"] },
  { id: "scotia-momentum-no-fee", name: "Scotia Momentum No-Fee Mastercard", issuer: "Scotiabank", annualFee: 0, rates: { dining: 0.005, grocery: 0.01, gas: 0.01, travel: 0.005, other: 0.005 }, badge: "💸 No-Fee Cashback", color: "#CC0000", description: "1% cashback on gas, groceries, drugstores & recurring bills. 0.5% on everything else. No annual fee.", img: "/cards/scotia-momentum-mastercard.avif", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/mastercard/momentum-no-fee-mastercard-card.html", perks: ["1% cashback on eligible gas, grocery & drugstore purchases", "1% on eligible recurring bill payments (utilities, gym memberships)", "0.5% on all other eligible purchases", "No annual fee", "Purchase security & extended warranty"] },
  { id: "scotiabank-value", name: "Scotiabank Value Visa", issuer: "Scotiabank", annualFee: 29, rates: { dining: 0.005, grocery: 0.005, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "📉 Low Rate", color: "#CC0000", description: "Low 12.99% interest rate. Best for carrying a balance occasionally.", img: "/cards/scotiabank-value.webp", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/value-card.html", perks: ["12.99% purchase interest rate", "Low balance transfer rate", "Purchase security", "$29/yr annual fee", "Simple rewards-free option"] },
  { id: "scotiabank-no-fee", name: "Scotiabank No-Fee Visa", issuer: "Scotiabank", annualFee: 0, rates: { dining: 0.005, grocery: 0.005, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "🆓 No Fee", color: "#CC0000", description: "Basic no-fee Visa. Entry-level card with no frills.", img: "/cards/scotia_no_fee_visa.webp", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards.html", perks: ["No annual fee", "Purchase security", "Online banking access", "Fraud monitoring", "Basic starter card"] },

  // ── TD BANK ───────────────────────────────────────────────
  { id: "td-aeroplan-platinum", name: "TD Aeroplan Visa Platinum", issuer: "TD Bank", annualFee: 89, rates: { dining: 0.0067, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.0067 }, badge: "✈️ Aeroplan Starter", color: "#00A758", description: "1x Aeroplan on gas, EV charging, groceries & Air Canada. 1 pt per $1.50 on everything else.", img: "/cards/td-aeroplan-platinum.jpeg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/aeroplan/", perks: ["1x Aeroplan Point per $1 on gas, EV charging, groceries & Air Canada purchases", "1x Aeroplan Point per $1.50 on all other purchases", "Earn points twice at 150+ Aeroplan partners & 200+ online retailers via Aeroplan eStore", "Travel insurance included", "$89/yr annual fee"] },
  { id: "td-aeroplan-privilege", name: "TD Aeroplan Visa Infinite Privilege", issuer: "TD Bank", annualFee: 599, rates: { dining: 0.015, grocery: 0.015, gas: 0.015, travel: 0.02, other: 0.0125 }, badge: "✈️ Aeroplan Elite", color: "#00A758", description: "2x Aeroplan on Air Canada. 1.5x on dining, grocery, gas, transit & travel. 1.25x on everything else.", img: "/cards/td-aeroplan-privilege.jpeg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/aeroplan/", perks: ["2x Aeroplan Points on eligible Air Canada & Air Canada Vacations purchases", "1.5x Aeroplan Points on dining, groceries, gas, EV charging, travel & transit", "1.25x Aeroplan Points on all other purchases", "Earn points twice at 150+ Aeroplan partners & 200+ online retailers via Aeroplan eStore", "Priority boarding · Maple Leaf Lounge access · $599/yr annual fee"] },
  { id: "td-cashback-infinite", name: "TD Cash Back Visa Infinite", issuer: "TD Bank", annualFee: 139, rates: { dining: 0.01, grocery: 0.03, gas: 0.03, travel: 0.01, other: 0.01 }, badge: "💵 3% Cashback", color: "#00A758", description: "3% cashback on groceries, gas, EV charging & transit. 3% on recurring bills & streaming. 1% on everything else.", img: "/cards/td-cashback-infinite.jpeg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/cash-back/", perks: ["3% cashback on groceries, gas, EV charging & public transit", "3% on recurring bill payments, streaming, digital gaming & media", "1% on all other purchases including dining & travel", "$139/yr annual fee"] },
  { id: "td-cashback-visa", name: "TD Cash Back Visa", issuer: "TD Bank", annualFee: 0, rates: { dining: 0.005, grocery: 0.01, gas: 0.01, travel: 0.005, other: 0.005 }, badge: "💸 No-Fee Cashback", color: "#00A758", description: "1% cashback on groceries, gas, EV charging & transit. 1% on recurring bills & streaming. 0.5% on everything else.", img: "/cards/td-cashback-visa.jpeg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/cash-back/", perks: ["1% cashback on groceries, gas, EV charging & public transit", "1% on recurring bill payments, streaming, digital gaming & media", "0.5% on all other purchases including dining & travel", "No annual fee"] },
  { id: "td-first-class", name: "TD First Class Travel Visa Infinite", issuer: "TD Bank", annualFee: 139, rates: { dining: 0.03, grocery: 0.03, gas: 0.01, travel: 0.04, other: 0.01 }, badge: "✈️ Travel Points", color: "#00A758", description: "8x TD Points via Expedia for TD. 6x on groceries, dining & transit. 4x on bills & streaming. 2x on everything else.", img: "/cards/td-first-class.jpeg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/travel/", perks: ["8x TD Rewards Points on travel booked via Expedia for TD", "6x TD Rewards Points on groceries, dining & public transit", "4x TD Rewards Points on recurring bills, streaming, digital gaming & media", "2x TD Rewards Points on all other purchases", "Up to 10,000 TD Rewards pts Birthday Bonus annually · $139/yr annual fee"] },
  { id: "td-platinum-travel", name: "TD Platinum Travel Visa", issuer: "TD Bank", annualFee: 89, rates: { dining: 0.0225, grocery: 0.0225, gas: 0.0075, travel: 0.03, other: 0.0075 }, badge: "✈️ Travel Starter", color: "#00A758", description: "6x TD Points via Expedia for TD. 4.5x on groceries, dining & transit. 3x on bills & streaming. 1.5x on everything else.", img: "/cards/td-platinum-travel.jpg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/travel/", perks: ["6x TD Rewards Points on travel via Expedia for TD", "4.5x TD Rewards Points on groceries, dining & public transit", "3x TD Rewards Points on recurring bills, streaming, digital gaming & media", "1.5x TD Rewards Points on all other purchases", "$89/yr annual fee"] },
  { id: "td-rewards-visa", name: "TD Rewards Visa", issuer: "TD Bank", annualFee: 0, rates: { dining: 0.015, grocery: 0.015, gas: 0.005, travel: 0.02, other: 0.005 }, badge: "🆓 No-Fee Points", color: "#00A758", description: "4x TD Points via Expedia for TD. 3x on groceries, dining & transit. 2x on bills & streaming. 1x on everything else. No fee.", img: "/cards/td-rewards-visa.jpg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/", perks: ["4x TD Rewards Points on travel via Expedia for TD", "3x TD Rewards Points on groceries, dining & public transit", "2x TD Rewards Points on recurring bills, streaming, digital gaming & media", "1x TD Rewards Points on all other purchases", "No annual fee"] },
  { id: "td-business-travel", name: "TD Business Travel Visa", issuer: "TD Bank", annualFee: 149, rates: { dining: 0.03, grocery: 0.01, gas: 0.03, travel: 0.045, other: 0.01 }, badge: "💼 Business Travel", color: "#00A758", description: "9x TD Points via Expedia for TD. 6x on dining, transit, EV charging, streaming, bills & foreign currency. Business card.", img: "/cards/td-business-travel.jpeg", bankUrl: "https://www.td.com/ca/en/business-banking/products/credit-cards/business-travel-visa/", perks: ["9x TD Rewards Points on travel via ExpediaForTD.com", "6x TD Rewards Points on dining, EV charging & public transit", "6x TD Rewards Points on streaming, digital gaming & recurring bills", "6x TD Rewards Points on foreign currency purchases", "2x TD Rewards Points on all other purchases · $149/yr annual fee"] },
  { id: "td-emerald", name: "TD Emerald Flex Rate Visa", issuer: "TD Bank", annualFee: 25, rates: { dining: 0.005, grocery: 0.005, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "📉 Flexible Rate", color: "#00A758", description: "Variable low interest rate. Good for those who occasionally carry a balance.", img: "/cards/td-emerald.png", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/", perks: ["Variable interest rate", "Low annual fee", "Purchase security", "Online banking access", "$25/yr annual fee"] },
  { id: "td-green", name: "TD Green Visa", issuer: "TD Bank", annualFee: 0, rates: { dining: 0.005, grocery: 0.005, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "🌱 Starter Card", color: "#00A758", description: "TD's most basic no-fee card. Simple, no rewards.", img: "/cards/td-green.jpeg", bankUrl: "https://www.td.com/ca/en/personal-banking/products/credit-cards/", perks: ["No annual fee", "Basic Visa benefits", "Fraud protection", "Online banking", "Good for credit building"] },

  // ── RBC ───────────────────────────────────────────────────
  { id: "rbc-avion-platinum", name: "RBC Avion Visa Platinum", issuer: "RBC", annualFee: 120, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "✈️ Avion Points", color: "#005DAA", description: "1x Avion point on all eligible purchases including travel. Transfer to 30+ airline partners.", img: "/cards/rbc-avion-platinum.jpeg", bankUrl: "https://www.rbcroyalbank.com/credit-cards/avion-platinum-visa.html", perks: ["1x Avion Point on travel-related purchases", "1x Avion Point on all other eligible purchases", "Transfer to 30+ airline partners", "Travel insurance included", "$120/yr annual fee"] },
  { id: "rbc-avion-privilege", name: "RBC Avion Visa Infinite Privilege", issuer: "RBC", annualFee: 399, rates: { dining: 0.0125, grocery: 0.0125, gas: 0.0125, travel: 0.0125, other: 0.0125 }, badge: "💎 Premium Avion", color: "#005DAA", description: "1.25x Avion on all qualifying purchases. Double redemption value on Business & First-Class tickets.", img: "/cards/rbc-avion-privilege.webp", bankUrl: "https://www.rbcroyalbank.com/credit-cards/avion-infinite-privilege.html", perks: ["1.25x Avion Points on all qualifying purchases", "Double redemption value on Business & First-Class tickets", "Priority airport check-in & lounge access", "Comprehensive travel insurance", "$399/yr annual fee · Requires $200,000 min personal income"] },
  { id: "rbc-ion-plus", name: "RBC ION+ Visa", issuer: "RBC", annualFee: 48, rates: { dining: 0.03, grocery: 0.03, gas: 0.03, travel: 0.01, other: 0.01 }, badge: "⚡ Everyday Earn", color: "#005DAA", description: "3x Avion points on groceries, dining, and gas. Great everyday earner for the price.", img: "/cards/rbc-ion-plus.webp", bankUrl: "https://www.rbcroyalbank.com/credit-cards/ion-plus-visa.html", perks: ["3x Avion on grocery, dining & gas", "1x on all other purchases", "ION+ Rewards redemption", "Purchase security", "$48/yr annual fee"] },
  { id: "rbc-ion", name: "RBC ION Visa", issuer: "RBC", annualFee: 0, rates: { dining: 0.01, grocery: 0.015, gas: 0.015, travel: 0.01, other: 0.01 }, badge: "🆓 No-Fee Earn", color: "#005DAA", description: "1.5x Avion on groceries, gas, rideshare & streaming. 1x on everything else. No annual fee.", img: "/cards/rbc-ion.webp", bankUrl: "https://www.rbcroyalbank.com/credit-cards/ion-visa.html", perks: ["1.5x Avion Points on groceries, gas, rideshare & streaming services", "1x Avion Point on all other qualifying purchases", "No annual fee", "Avion Rewards program", "Easy mobile management"] },
  { id: "rbc-cashback", name: "RBC Cash Back Mastercard", issuer: "RBC", annualFee: 0, rates: { dining: 0.01, grocery: 0.02, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "💸 No-Fee Cashback", color: "#005DAA", description: "Up to 2% cashback on groceries. 1% on all other everyday purchases. No annual fee.", img: "/cards/rbc-cashback-mastercard.jpeg", bankUrl: "https://www.rbcroyalbank.com/credit-cards/cash-back-mastercard.html", perks: ["Up to 2% cashback on grocery store purchases", "1% cashback on all other everyday purchases", "No annual fee", "Purchase security", "Easy cashback redemption"] },
  { id: "rbc-cashback-world-elite", name: "RBC Cash Back Preferred World Elite Mastercard", issuer: "RBC", annualFee: 99, rates: { dining: 0.015, grocery: 0.015, gas: 0.015, travel: 0.015, other: 0.015 }, badge: "💵 Flat-Rate Cashback", color: "#005DAA", description: "Up to 1.5% cash back on all purchases including online & wholesale retailers.", img: "/cards/rbc-cashback-world-elite.webp", bankUrl: "https://www.rbcroyalbank.com/credit-cards/cash-back-world-elite-mastercard.html", perks: ["Up to 1.5% cash back on all purchases", "Includes online & wholesale retailers", "World Elite Mastercard benefits", "Travel insurance included", "$99/yr annual fee"] },
  { id: "rbc-more-rewards", name: "More Rewards RBC Visa", issuer: "RBC", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.006, other: 0.006 }, badge: "🛒 More Rewards", color: "#005DAA", description: "5x More Rewards on groceries, pharmacy, gas & dining. 3x on everything else. No annual fee.", img: "/cards/rbc-more-rewards.jpeg", bankUrl: "https://www.rbcroyalbank.com/credit-cards/more-rewards-visa.html", perks: ["5 More Rewards pts/$1 at 700+ grocery, pharmacy & partner locations", "5 More Rewards pts/$1 on gas, EV charging & dining", "3 More Rewards pts/$1 on all other purchases", "Redeem at Save-On-Foods, Urban Fare & More Rewards partners", "No annual fee"] },
  { id: "rbc-more-rewards-infinite", name: "More Rewards RBC Visa Infinite", issuer: "RBC", annualFee: 0, rates: { dining: 0.016, grocery: 0.016, gas: 0.016, travel: 0.008, other: 0.008 }, badge: "🛒 More Rewards", color: "#005DAA", description: "8x More Rewards on groceries, pharmacy, gas, EV & dining. 4x on everything else. No annual fee.", img: "/cards/rbc-more-rewards-infinite.jpeg", bankUrl: "https://www.rbcroyalbank.com/credit-cards/more-rewards-visa-infinite.html", perks: ["8 More Rewards pts/$1 at 700+ grocery, pharmacy & partner locations", "8 More Rewards pts/$1 on gas, EV charging & dining", "4 More Rewards pts/$1 on all other purchases", "Redeem at Save-On-Foods, Urban Fare & More Rewards partners", "No annual fee"] },
  { id: "rbc-westjet-world-elite", name: "RBC WestJet World Elite Mastercard", issuer: "RBC", annualFee: 139, rates: { dining: 0.015, grocery: 0.02, gas: 0.02, travel: 0.02, other: 0.015 }, badge: "✈️ WestJet Dollars", color: "#0A5FA8", description: "2 WestJet dollars/$1 on WestJet, groceries & transportation. 1.5 on everything else.", img: "/cards/rbc-westjet-world-elite.webp", bankUrl: "https://www.westjet.com/en-ca/credit-cards/world-elite-mastercard", perks: ["2 WestJet dollars/$1 on WestJet flights, WestJet Vacations & Sunwing Vacations", "2 WestJet dollars/$1 on groceries, gas, EV charging, transit & rideshare", "1.5 WestJet dollars/$1 on all other everyday purchases", "Annual companion voucher · Free checked bag on WestJet", "$139/yr annual fee · Requires $80,000 min personal income"] },
  { id: "rbc-westjet", name: "WestJet RBC Mastercard", issuer: "RBC", annualFee: 39, rates: { dining: 0.015, grocery: 0.01, gas: 0.01, travel: 0.015, other: 0.01 }, badge: "✈️ WestJet Starter", color: "#0A5FA8", description: "1.5 WestJet dollars on WestJet, dining, food delivery & streaming. 1 WestJet dollar on everything else.", img: "/cards/rbc-westjet.webp", bankUrl: "https://www.westjet.com/en-ca/credit-cards/mastercard", perks: ["1.5 WestJet dollars/$1 on WestJet flights, WestJet Vacations & Sunwing Vacations", "1.5 WestJet dollars/$1 on restaurants, food delivery, streaming & digital gaming", "1 WestJet dollar/$1 on all other everyday purchases", "Free checked bag on WestJet", "$39/yr annual fee"] },
  { id: "rbc-british-airways", name: "RBC British Airways Visa Infinite", issuer: "RBC", annualFee: 165, rates: { dining: 0.02, grocery: 0.01, gas: 0.01, travel: 0.03, other: 0.01 }, badge: "✈️ Avios Points", color: "#075AAA", description: "3 Avios on British Airways. 2 Avios on dining & food delivery. 1 Avios on everything else.", img: "/cards/rbc-british-airways.webp", bankUrl: "https://www.rbcroyalbank.com/credit-cards/british-airways-visa-infinite.html", perks: ["3 Avios/$1 on British Airways purchases", "2 Avios/$1 on dining & food delivery", "1 Avios/$1 on all other qualifying purchases", "Avios travel redemptions", "$165/yr annual fee"] },

  // ── BMO ───────────────────────────────────────────────────
  { id: "bmo-eclipse-rise", name: "BMO Eclipse Rise Visa", issuer: "BMO", annualFee: 0, rates: { dining: 0.0167, grocery: 0.0167, gas: 0.0067, travel: 0.0067, other: 0.0067 }, badge: "🆓 No-Fee Rewards", color: "#0079C1", description: "5x BMO Rewards points per $2 on groceries, dining, takeout & recurring bills. 1x on everything else. No annual fee.", img: "/cards/bmo-eclipse-rise.jpg", bankUrl: "https://www.bmo.com/main/personal/credit-cards/", perks: ["5x BMO Rewards points per $2 on recurring bills, groceries, dining & takeout", "1x BMO Rewards point per $1 on all other purchases", "3 months complimentary Instacart+ with $5 monthly credit", "No annual fee", "BMO Rewards program"] },
  { id: "bmo-ascend-world-elite", name: "BMO Ascend World Elite Mastercard", issuer: "BMO", annualFee: 150, rates: { dining: 0.02, grocery: 0.0067, gas: 0.0067, travel: 0.0333, other: 0.0067 }, badge: "✈️ Travel Rewards", color: "#0079C1", description: "5x BMO Rewards on travel. 3x on dining, entertainment & recurring bills. 1x on everything else.", img: "/cards/bmo-ascend.webp", bankUrl: "https://www.bmo.com/main/personal/credit-cards/bmo-ascend-world-elite-mastercard/", perks: ["5x BMO Rewards points per $1 on eligible travel", "3x per $1 on eligible dining", "3x per $1 on eligible entertainment", "3x per $1 on recurring bill payments", "1x per $1 on everything else · $150/yr annual fee"] },
  { id: "bmo-eclipse-privilege", name: "BMO Eclipse Visa Infinite Privilege", issuer: "BMO", annualFee: 599, rates: { dining: 0.0333, grocery: 0.0333, gas: 0.0333, travel: 0.0333, other: 0.0067 }, badge: "💎 Premium Rewards", color: "#0079C1", description: "5x BMO Rewards on groceries, dining, gas, drugstore & travel. 1x on everything else.", img: "/cards/bmo-eclipse-privilege.jpg", bankUrl: "https://www.bmo.com/main/personal/credit-cards/bmo-eclipse-visa-infinite-privilege/", perks: ["5x BMO Rewards points per $1 on groceries", "5x per $1 on dining & takeout", "5x per $1 on gas", "5x per $1 on drugstore (healthcare & beauty)", "5x per $1 on travel · $599/yr · Requires $150,000 min personal income"] },
  { id: "bmo-viporter", name: "BMO VIPorter Mastercard", issuer: "BMO", annualFee: 89, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.005 }, badge: "✈️ Porter Points", color: "#0079C1", description: "2x VIPorter points on Porter. 1x on travel, gas, groceries, dining & hotels. 0.5x everywhere else.", img: "/cards/bmo-viporter.webp", bankUrl: "https://www.bmo.com/main/personal/credit-cards/bmo-viporter-mastercard/", perks: ["2x VIPorter points per $1 on Porter purchases", "1x per $1 on everyday travel (gas & transportation)", "1x per $1 on groceries & dining", "1x per $1 on hotel accommodations", "0.5x per $1 everywhere else · $89/yr annual fee"] },
  { id: "bmo-viporter-world-elite", name: "BMO VIPorter World Elite Mastercard", issuer: "BMO", annualFee: 199, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.02, other: 0.01 }, badge: "✈️ Porter Elite", color: "#0079C1", description: "3x VIPorter points on Porter. 2x on travel, gas, groceries, dining & hotels. 1x everywhere else.", img: "/cards/bmo-viporter-world-elite.webp", bankUrl: "https://www.bmo.com/main/personal/credit-cards/bmo-viporter-world-elite-mastercard/", perks: ["3x VIPorter points per $1 on Porter purchases", "2x per $1 on everyday travel (gas & transportation)", "2x per $1 on groceries & dining", "2x per $1 on hotel accommodations", "1x per $1 everywhere else · $199/yr annual fee"] },
  { id: "bmo-cashback-world-elite", name: "BMO CashBack World Elite Mastercard", issuer: "BMO", annualFee: 120, rates: { dining: 0.01, grocery: 0.05, gas: 0.03, travel: 0.01, other: 0.01 }, badge: "🛒 5% Groceries", color: "#0079C1", description: "5% on groceries, 4% on transit, 3% on gas, 2% on recurring bills. Highest grocery cashback in Canada.", img: "/cards/bmo-cashback-world-elite.webp", bankUrl: "https://www.bmo.com/main/personal/credit-cards/bmo-cashback-world-elite-mastercard/", perks: ["5% cashback on groceries (highest in Canada)", "4% on transit, ride sharing, taxis & public transportation", "3% on gas & EV charging", "2% on recurring bills (phone, gym, streaming)", "1% on all other purchases · $120/yr annual fee"] },
  { id: "bmo-cashback", name: "BMO CashBack Mastercard", issuer: "BMO", annualFee: 0, rates: { dining: 0.005, grocery: 0.03, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "🛒 Grocery Cashback", color: "#0079C1", description: "3% cashback on groceries. 1% on recurring bills. 0.5% on everything else. No annual fee.", img: "/cards/bmo-cashback.webp", bankUrl: "https://www.bmo.com/main/personal/credit-cards/bmo-cashback-mastercard/", perks: ["3% cashback on grocery purchases", "1% cashback on recurring bill payments (streaming, subscriptions, utilities)", "0.5% cashback on all other purchases", "No annual fee", "Unlimited cashback"] },
  { id: "bmo-preferred-rate", name: "BMO Preferred Rate Mastercard", issuer: "BMO", annualFee: 20, rates: { dining: 0.005, grocery: 0.005, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "📉 Low Interest", color: "#0079C1", description: "Low 12.99% purchase interest rate. Best for occasional balance carriers.", img: "/cards/bmo-preferred-rate.webp", bankUrl: "https://www.bmo.com/main/personal/credit-cards/bmo-preferred-rate-mastercard/", perks: ["12.99% purchase interest rate", "Low balance transfer rate", "Purchase security", "Extended warranty", "$20/yr annual fee"] },
  { id: "bmo-student", name: "BMO CashBack Mastercard for Students", issuer: "BMO", annualFee: 0, rates: { dining: 0.005, grocery: 0.03, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "🎓 Student Cashback", color: "#0079C1", description: "3% cashback on groceries. 1% on recurring bills. 0.5% on everything else. No annual fee, no minimum income.", img: "/cards/bmo-student-cashback-mastercard.webp", bankUrl: "https://www.bmo.com/main/personal/credit-cards/", perks: ["3% cashback on grocery purchases", "1% cashback on recurring bill payments (mobile, streaming, subscriptions)", "0.5% cashback on all other purchases", "No annual fee · No minimum income required", "Student-friendly credit building"] },

  // ── CIBC ──────────────────────────────────────────────────
  { id: "cibc-aventura-infinite", name: "CIBC Aventura Visa Infinite", issuer: "CIBC", annualFee: 139, rates: { dining: 0.01, grocery: 0.015, gas: 0.015, travel: 0.02, other: 0.01 }, badge: "✈️ Aventura Points", color: "#C41230", description: "2x Aventura on travel via CIBC Rewards Centre. 1.5x on gas, EV, groceries & drugstores. 1x everything else.", img: "/cards/cibc-aventura-infinite.webp", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aventura-visa-infinite.html", perks: ["2x Aventura Points on travel booked via CIBC Rewards Centre (Expedia)", "1.5x Aventura Points on gas, EV charging, groceries & drugstores", "1x Aventura Point on all other purchases", "Up to 10¢/L off eligible gas", "$139/yr annual fee"] },
  { id: "cibc-aventura-privilege", name: "CIBC Aventura Visa Infinite Privilege", issuer: "CIBC", annualFee: 499, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.03, other: 0.0125 }, badge: "💎 Aventura Elite", color: "#C41230", description: "3x Aventura on travel via CIBC Rewards Centre. 2x on dining, entertainment, transport, gas & groceries. 1.25x else.", img: "/cards/cibc_aventura_cibc.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aventura-visa-infinite-privilege.html", perks: ["3x Aventura Points on travel booked via CIBC Rewards Centre (Expedia)", "2x Aventura Points on dining, entertainment, transport, gas, EV charging & groceries", "1.25x Aventura Points on all other purchases", "Airport lounge access · Up to 10¢/L off gas", "$499/yr annual fee"] },
  { id: "cibc-aventura-gold", name: "CIBC Aventura Gold Visa", issuer: "CIBC", annualFee: 139, rates: { dining: 0.01, grocery: 0.015, gas: 0.015, travel: 0.02, other: 0.01 }, badge: "✈️ Aventura Points", color: "#C41230", description: "2x Aventura on travel via CIBC Rewards Centre. 1.5x on gas, EV, groceries & drugstores. 1x everything else.", img: "/cards/cibc-aventura-gold.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aventura-gold-visa.html", perks: ["2x Aventura Points on travel booked via CIBC Rewards Centre (Expedia)", "1.5x Aventura Points on gas, EV charging, groceries & drugstores", "1x Aventura Point on all other purchases", "Up to 10¢/L off eligible gas", "$139/yr annual fee"] },
  { id: "cibc-aventura-visa", name: "CIBC Aventura Visa", issuer: "CIBC", annualFee: 0, rates: { dining: 0.005, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.005 }, badge: "🆓 No-Fee Aventura", color: "#C41230", description: "1x Aventura on gas, EV, groceries, drugstores & travel. 1 pt per $2 on everything else. No annual fee.", img: "/cards/cibc-aventura-visa.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aventura-visa.html", perks: ["1x Aventura Point on gas, EV charging, groceries & drugstores", "1x Aventura Point on travel booked via CIBC Rewards Centre (Expedia)", "1 Aventura Point per $2 on all other purchases", "Up to 10¢/L off eligible gas", "No annual fee"] },
  { id: "cibc-adapta", name: "CIBC Adapta Mastercard", issuer: "CIBC", annualFee: 0, rates: { dining: 0.015, grocery: 0.015, gas: 0.015, travel: 0.02, other: 0.01 }, badge: "🔄 Adaptive Earn", color: "#C41230", description: "2x Adapta on travel via CIBC by Expedia. 1.5x on your top 3 spend categories each month. 1x else. No annual fee.", img: "/cards/cibc-adapta.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/adapta-mastercard.html", perks: ["2x Adapta Points on travel booked via CIBC by Expedia", "1.5x Adapta Points on your top 3 spend categories each month (dynamic)", "1x Adapta Point on all other purchases", "Bonus categories adjust automatically to your spending", "No annual fee · Estimate assumes grocery, dining & gas as your top 3"] },
  { id: "cibc-adapta-student", name: "CIBC Adapta Mastercard for Students", issuer: "CIBC", annualFee: 0, rates: { dining: 0.015, grocery: 0.015, gas: 0.015, travel: 0.02, other: 0.01 }, badge: "🎓 Student Adaptive", color: "#C41230", description: "2x Adapta on travel via CIBC by Expedia. 1.5x on your top 3 spend categories each month. 1x else. For students.", img: "/cards/cibc-adapta.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/adapta-mastercard.html", perks: ["2x Adapta Points on travel booked via CIBC by Expedia", "1.5x Adapta Points on your top 3 spend categories each month (dynamic)", "1x Adapta Point on all other purchases", "No annual fee · No minimum income required", "Estimate assumes grocery, dining & gas as your top 3"] },
  { id: "cibc-aventura-student", name: "CIBC Aventura Visa for Students", issuer: "CIBC", annualFee: 0, rates: { dining: 0.005, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.005 }, badge: "🎓 Student Aventura", color: "#C41230", description: "1x Aventura on gas, EV, groceries, drugstores & travel. 1 pt per $2 on everything else. For students.", img: "/cards/cibc-aventura-visa.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aventura-visa.html", perks: ["1x Aventura Point on gas, EV charging, groceries & drugstores", "1x Aventura Point on travel booked via CIBC Rewards Centre (Expedia)", "1 Aventura Point per $2 on all other purchases", "No annual fee · No minimum income required", "Up to 10¢/L off eligible gas"] },
  { id: "cibc-aeroplan-student", name: "CIBC Aeroplan Visa for Students", issuer: "CIBC", annualFee: 0, rates: { dining: 0.0067, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.0067 }, badge: "🎓 Student Aeroplan", color: "#C41230", description: "1x Aeroplan on gas, EV, groceries & Air Canada. 1 pt per $1.50 on everything else. For students.", img: "/cards/cibc_areoplane_visa.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aeroplan.html", perks: ["1x Aeroplan Point on gas, EV charging, groceries & Air Canada purchases", "1 Aeroplan Point per $1.50 on all other purchases", "Earn points twice at 150+ Aeroplan partners & 170+ online retailers via Aeroplan eStore", "No annual fee · No minimum income required", "Up to 10¢/L off gas with Journie Rewards"] },
  { id: "cibc-classic-student", name: "CIBC Classic Visa for Students", issuer: "CIBC", annualFee: 0, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "🎓 Student Starter", color: "#C41230", description: "No-fee CIBC Visa for students with purchase security & extended protection. No rewards.", img: "/cards/cibc-classic-visa.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards.html", perks: ["No annual fee", "Purchase Security & Extended Protection", "No minimum income required", "No rewards or cashback", "Great for building credit as a student"] },
  { id: "cibc-dividend-infinite", name: "CIBC Dividend Visa Infinite", issuer: "CIBC", annualFee: 120, rates: { dining: 0.02, grocery: 0.04, gas: 0.04, travel: 0.02, other: 0.01 }, badge: "💵 4% Cashback", color: "#C41230", description: "4% cashback on gas, EV & groceries. 2% on transport, dining, recurring bills & travel. 1% everything else.", img: "/cards/cibc-dividend-infinite.webp", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/dividend-visa-infinite.html", perks: ["4% cashback on gas, EV charging & groceries", "2% on transportation, dining, recurring payments & travel via CIBC by Expedia", "1% cashback on everything else", "Up to 10¢/L off gas with Journie Rewards", "$120/yr annual fee"] },
  { id: "cibc-dividend-platinum", name: "CIBC Dividend Platinum Visa", issuer: "CIBC", annualFee: 99, rates: { dining: 0.02, grocery: 0.03, gas: 0.03, travel: 0.02, other: 0.01 }, badge: "💵 3% Cashback", color: "#C41230", description: "3% cashback on gas, EV & groceries. 2% on transport, dining, recurring bills & travel. 1% everything else.", img: "/cards/cibc-dividend-platinum.webp", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/dividend-platinum-visa.html", perks: ["3% cashback on gas, EV charging & groceries", "2% on transportation, dining, recurring payments & travel via CIBC by Expedia", "1% cashback on everything else", "Up to 10¢/L off gas with Journie Rewards", "$99/yr annual fee"] },
  { id: "cibc-costco", name: "CIBC Costco Mastercard", issuer: "CIBC", annualFee: 0, rates: { dining: 0.03, grocery: 0.01, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "🏪 Costco Card", color: "#C41230", description: "3% at restaurants & Costco gas. 2% at other gas, EV & Costco.ca. 1% everything else incl in-warehouse Costco.", img: "/cards/cibc-costco.png", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/costco-mastercard.html", perks: ["3% cashback at restaurants & Costco gas", "2% at other gas stations, EV charging & Costco.ca", "1% on all other purchases including in-warehouse Costco", "No annual fee (Costco membership required)", "Accepted everywhere Mastercard is accepted"] },
  { id: "cibc-dividend-visa", name: "CIBC Dividend Visa", issuer: "CIBC", annualFee: 0, rates: { dining: 0.01, grocery: 0.02, gas: 0.01, travel: 0.01, other: 0.005 }, badge: "💸 No-Fee Cashback", color: "#C41230", description: "2% cashback on groceries. 1% on gas, EV, transport, dining, bills & travel. 0.5% everything else. No fee.", img: "/cards/cibc-dividend-visa.webp", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/dividend-visa.html", perks: ["2% cashback on groceries", "1% on gas, EV charging, transportation, dining, recurring payments & travel via CIBC by Expedia", "0.5% cashback on everything else", "Up to 10¢/L off gas with Journie Rewards", "No annual fee"] },
  { id: "cibc-aeroplan-infinite", name: "CIBC Aeroplan Visa Infinite", issuer: "CIBC", annualFee: 139, rates: { dining: 0.01, grocery: 0.015, gas: 0.015, travel: 0.015, other: 0.01 }, badge: "✈️ Aeroplan Miles", color: "#C41230", description: "1.5x Aeroplan on gas, EV, groceries & Air Canada. 1x on everything else.", img: "/cards/cibc-aeroplan-infinite.webp", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aeroplan-visa-infinite.html", perks: ["1.5x Aeroplan Points on gas, EV charging, groceries & Air Canada purchases", "1x Aeroplan Point on all other purchases", "Earn points twice at 150+ Aeroplan partners & 170+ online retailers via Aeroplan eStore", "Up to 10¢/L off eligible gas", "$139/yr annual fee"] },
  { id: "cibc-aeroplan-privilege", name: "CIBC Aeroplan Visa Infinite Privilege", issuer: "CIBC", annualFee: 599, rates: { dining: 0.015, grocery: 0.015, gas: 0.015, travel: 0.015, other: 0.0125 }, badge: "✈️ Aeroplan Elite", color: "#C41230", description: "2x Aeroplan on Air Canada. 1.5x on gas, EV, groceries, travel & dining. 1.25x on everything else.", img: "/cards/cibc_aeroplane_ifinite_privilge.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aeroplan-visa-infinite-privilege.html", perks: ["2x Aeroplan Points on Air Canada & Air Canada Vacations", "1.5x Aeroplan Points on gas, EV charging, groceries, travel & dining", "1.25x Aeroplan Points on all other purchases", "Earn points twice at 150+ Aeroplan partners & 170+ online retailers · Up to 10¢/L off gas with Journie", "Priority boarding · Lounge access · $599/yr annual fee"] },
  { id: "cibc-aeroplan-no-fee", name: "CIBC Aeroplan Visa", issuer: "CIBC", annualFee: 0, rates: { dining: 0.0067, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.0067 }, badge: "✈️ No-Fee Aeroplan", color: "#C41230", description: "1x Aeroplan on gas, EV, groceries & Air Canada. 1 pt per $1.50 on everything else. No annual fee.", img: "/cards/cibc_areoplane_visa.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/aeroplan.html", perks: ["1x Aeroplan Point on gas, EV charging, groceries & Air Canada purchases", "1 Aeroplan Point per $1.50 on all other purchases", "Earn points twice at 150+ Aeroplan partners & 170+ online retailers via Aeroplan eStore", "Up to 10¢/L off gas with Journie Rewards", "No annual fee"] },
  { id: "cibc-select", name: "CIBC Select Visa", issuer: "CIBC", annualFee: 29, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "📉 Low Interest", color: "#C41230", description: "13.99% purchase & cash interest rate. No rewards. Best for carrying a balance.", img: "/cards/cibc_select_visa.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/select-visa.html", perks: ["13.99% purchase interest rate", "13.99% cash interest rate", "No rewards or cashback", "Low balance transfer option", "$29/yr annual fee"] },
  { id: "cibc-classic", name: "CIBC Classic Visa", issuer: "CIBC", annualFee: 0, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "🌱 Starter Card", color: "#C41230", description: "Basic no-fee CIBC Visa with purchase security & extended protection. No rewards.", img: "/cards/cibc-classic-visa.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards.html", perks: ["No annual fee", "Purchase Security & Extended Protection", "No rewards or cashback", "Fraud protection", "Good for building credit"] },

  // ── NATIONAL BANK ─────────────────────────────────────────
  { id: "nbc-world-elite", name: "National Bank World Elite Mastercard", issuer: "National Bank", annualFee: 150, rates: { dining: 0.05, grocery: 0.05, gas: 0.02, travel: 0.02, other: 0.01 }, badge: "🛒 Grocery & Dining", color: "#ED1C24", description: "5x points on groceries & restaurants. 2x on gas, EV, bills & À la Carte Travel. 1x everything else.", img: "/cards/nbc-world-elite.png", bankUrl: "https://www.nbc.ca/personal/credit-cards/world-elite-mastercard.html", perks: ["5x points on groceries & restaurants", "2x on gas, EV charging, recurring bills & À la Carte Travel", "1x points on all other purchases", "Airport lounge access · Comprehensive travel insurance", "$150/yr annual fee"] },
  { id: "nbc-world", name: "National Bank Platinum Mastercard", issuer: "National Bank", annualFee: 70, rates: { dining: 0.02, grocery: 0.02, gas: 0.015, travel: 0.015, other: 0.0067 }, badge: "💳 Platinum Points", color: "#ED1C24", description: "2x points on groceries & restaurants. 1.5x on gas, EV, bills & À la Carte Travel. 1 pt per $1.50 else.", img: "/cards/nbc-world.png", bankUrl: "https://www.nbc.ca/personal/credit-cards.html", perks: ["2x points on groceries & restaurants", "1.5x on gas, EV charging, recurring bills & À la Carte Travel", "1 point per $1.50 on all other purchases", "Travel insurance included", "$70/yr annual fee"] },
  { id: "nbc-world-mastercard", name: "National Bank World Mastercard", issuer: "National Bank", annualFee: 115, rates: { dining: 0.02, grocery: 0.02, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "💳 World Points", color: "#ED1C24", description: "Up to 2 points per $1 spent. Conditions apply. À la Carte Rewards program.", img: "/cards/nbc-world-mastercard.png", bankUrl: "https://www.nbc.ca/personal/credit-cards.html", perks: ["Up to 2 points per $1 on eligible purchases (conditions apply)", "1 point per $1 base earn", "À la Carte Rewards redemption", "Travel insurance included", "$115/yr annual fee"] },
  { id: "nbc-allure", name: "National Bank Allure Mastercard", issuer: "National Bank", annualFee: 0, rates: { dining: 0.005, grocery: 0.01, gas: 0.01, travel: 0.005, other: 0.01 }, badge: "💸 No-Fee Cashback", color: "#ED1C24", description: "Up to 1% cashback on gas, groceries & online purchases. No annual fee.", img: "/cards/nbc-allure.png", bankUrl: "https://www.nbc.ca/personal/credit-cards.html", perks: ["Up to 1% cashback on gas, groceries & online purchases", "Cashback on everyday spending", "No annual fee", "No minimum income required", "Mastercard benefits & protections"] },
  { id: "nbc-mycredit", name: "National Bank mycredit Mastercard", issuer: "National Bank", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "💸 No-Fee Cashback", color: "#ED1C24", description: "Up to 1% cashback. Mobile device & extended warranty protection. No annual fee.", img: "/cards/nbc-mycredit.png", bankUrl: "https://www.nbc.ca/personal/credit-cards.html", perks: ["Up to 1% cashback on eligible purchases (conditions apply)", "Mobile device insurance (theft/damage up to 2 years)", "Up to double the manufacturer warranty", "No annual fee", "No minimum income required"] },
  { id: "nbc-echo", name: "National Bank ECHO Cashback Mastercard", issuer: "National Bank", annualFee: 0, rates: { dining: 0.005, grocery: 0.015, gas: 0.015, travel: 0.005, other: 0.015 }, badge: "💸 No-Fee Cashback", color: "#ED1C24", description: "Up to 1.5% cashback on gas, groceries & online purchases. No annual fee.", img: "/cards/nbc-echo.png", bankUrl: "https://www.nbc.ca/personal/credit-cards.html", perks: ["Up to 1.5% cashback on gas, groceries & online purchases", "Cashback on everyday spending", "No annual fee", "Purchase security", "Mastercard benefits & protections"] },
  { id: "nbc-syncro", name: "National Bank Syncro Mastercard", issuer: "National Bank", annualFee: 35, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "📉 Low Interest", color: "#ED1C24", description: "8.90% purchase interest rate, 12.90% on balance transfers & cash advances. No rewards.", img: "/cards/nbc-syncro.png", bankUrl: "https://www.nbc.ca/personal/credit-cards.html", perks: ["8.90% purchase interest rate", "12.90% on balance transfers & cash advances", "No rewards or cashback", "Low-interest focus", "$35/yr annual fee"] },

  // ── DESJARDINS ────────────────────────────────────────────
  { id: "desjardins-odyssey-world", name: "Desjardins Odyssey World Elite Mastercard", issuer: "Desjardins", annualFee: 130, rates: { dining: 0.03, grocery: 0.03, gas: 0.02, travel: 0.02, other: 0.015 }, badge: "🌍 Quebec Top Card", color: "#009A44", description: "Top Desjardins card. 3x on dining and groceries, strong insurance.", img: "", bankUrl: "https://www.desjardins.com/ca/personal/accounts-services/credit-cards.html", perks: ["3x BONUSDOLLARS on dining & grocery", "2x on gas & travel", "Lounge access", "Comprehensive travel insurance", "$130/yr annual fee"] },
  { id: "desjardins-odyssey", name: "Desjardins Odyssey Visa Infinite", issuer: "Desjardins", annualFee: 100, rates: { dining: 0.02, grocery: 0.02, gas: 0.015, travel: 0.015, other: 0.01 }, badge: "✈️ Odyssey Points", color: "#009A44", description: "Earn Odyssey points on everyday spending. Good travel card.", img: "", bankUrl: "https://www.desjardins.com/ca/personal/accounts-services/credit-cards.html", perks: ["2x on dining & groceries", "1.5x on gas & travel", "Travel insurance", "BONUSDOLLARS rewards", "$100/yr annual fee"] },
  { id: "desjardins-cash-world", name: "Desjardins Cash Back World Elite Mastercard", issuer: "Desjardins", annualFee: 100, rates: { dining: 0.04, grocery: 0.03, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "💵 Cash Back", color: "#009A44", description: "4% cashback on dining, 3% on groceries. Solid cashback choice.", img: "", bankUrl: "https://www.desjardins.com/ca/personal/accounts-services/credit-cards.html", perks: ["4% cashback on dining", "3% on groceries", "2% on gas", "1% on everything else", "$100/yr annual fee"] },
  { id: "desjardins-visa-infinite", name: "Desjardins Visa Infinite Privilege", issuer: "Desjardins", annualFee: 95, rates: { dining: 0.02, grocery: 0.02, gas: 0.015, travel: 0.02, other: 0.01 }, badge: "💳 Visa Infinite", color: "#009A44", description: "Earn BONUSDOLLARS on all spending. Travel insurance included.", img: "", bankUrl: "https://www.desjardins.com/ca/personal/accounts-services/credit-cards.html", perks: ["2x BONUSDOLLARS on dining & travel", "1.5x on gas", "Travel insurance", "Purchase protection", "$95/yr annual fee"] },
  { id: "desjardins-visa", name: "Desjardins Visa", issuer: "Desjardins", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "🆓 No-Fee Visa", color: "#009A44", description: "No annual fee Desjardins Visa with basic rewards.", img: "", bankUrl: "https://www.desjardins.com/ca/personal/accounts-services/credit-cards.html", perks: ["BONUSDOLLARS on purchases", "No annual fee", "Basic insurance", "Online banking", "Caisse member benefits"] },
  { id: "caisse-visa", name: "Desjardins Classic Visa", issuer: "Desjardins", annualFee: 0, rates: { dining: 0.005, grocery: 0.005, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "🌱 Basic Visa", color: "#009A44", description: "Basic no-fee Visa from Desjardins. Credit building.", img: "", bankUrl: "https://www.desjardins.com/ca/personal/accounts-services/credit-cards.html", perks: ["No annual fee", "Visa benefits", "Fraud protection", "Online banking", "Caisse network"] },

  // ── MBNA ──────────────────────────────────────────────────
  { id: "mbna-rewards-world-elite", name: "MBNA Rewards World Elite Mastercard", issuer: "MBNA", annualFee: 120, rates: { dining: 0.05, grocery: 0.05, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "🛒 5x Categories", color: "#003087", description: "5x points on restaurants, groceries, digital media, memberships & utilities. 1x everything else.", img: "/cards/mbna-creditcard-rewards-world-elite.png", bankUrl: "https://www.mbna.ca/en/credit-cards.html", perks: ["5x points on restaurants, groceries, digital media, memberships & household utilities (until $50k/category/yr)", "1x point on all other purchases", "Annual Birthday Bonus: 10% of prior-year points (max 15,000)", "World Elite Mastercard benefits", "$120/yr annual fee"] },
  { id: "mbna-rewards-platinum", name: "MBNA Rewards Platinum Plus Mastercard", issuer: "MBNA", annualFee: 0, rates: { dining: 0.02, grocery: 0.02, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "🆓 No-Fee Points", color: "#003087", description: "2x points on restaurants, groceries, digital media, memberships & utilities. 1x else. 4x intro for 90 days.", img: "/cards/MBNA-credit-card-mbna-rewards.png", bankUrl: "https://www.mbna.ca/en/credit-cards.html", perks: ["2x points on restaurants, groceries, digital media, memberships & household utilities (up to $10k/category/yr)", "4x points on those categories for the first 90 days", "1x point on all other purchases", "Annual Birthday Bonus: 10% of prior-year points (max 10,000)", "No annual fee"] },
  { id: "mbna-true-line", name: "MBNA True Line Mastercard", issuer: "MBNA", annualFee: 0, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "📉 Low Interest", color: "#003087", description: "12.99% purchase interest rate. No rewards. No annual fee. Best for carrying a balance.", img: "/cards/MBNA-true-line.png", bankUrl: "https://www.mbna.ca/en/credit-cards.html", perks: ["12.99% purchase interest rate", "No annual fee", "No rewards or cashback", "Balance transfer option", "Low-interest focus"] },
  { id: "mbna-true-line-gold", name: "MBNA True Line Gold Mastercard", issuer: "MBNA", annualFee: 39, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "📉 Lowest Rate", color: "#003087", description: "10.99% purchase interest rate (MBNA’s lowest). 13.99% on balance transfers. No rewards.", img: "/cards/MBNA_true-line-gold.png", bankUrl: "https://www.mbna.ca/en/credit-cards.html", perks: ["10.99% purchase interest rate (MBNA lowest)", "13.99% on balance transfers", "No rewards or cashback", "Low-interest focus", "$39/yr annual fee"] },
  { id: "mbna-smart-cash", name: "MBNA Smart Cash Platinum Plus Mastercard", issuer: "MBNA", annualFee: 0, rates: { dining: 0.005, grocery: 0.02, gas: 0.02, travel: 0.005, other: 0.005 }, badge: "⛽ Gas & Grocery", color: "#003087", description: "2% cashback on gas & groceries ($500/mo cap). 0.5% on everything else. No annual fee.", img: "/cards/mbna_smart-cash.png", bankUrl: "https://www.mbna.ca/en/credit-cards.html", perks: ["2% cashback on gas & groceries (up to $500 monthly spend per category)", "0.5% cashback on all other eligible purchases", "No annual fee", "Automatic cashback", "Mastercard benefits"] },
  { id: "mbna-smart-cash-world", name: "MBNA Smart Cash World Mastercard", issuer: "MBNA", annualFee: 39, rates: { dining: 0.01, grocery: 0.02, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "⛽ Gas & Grocery", color: "#003087", description: "2% cashback on gas & groceries. 1% on everything else. Includes rental car coverage.", img: "/cards/MBNA-smart-cash-world.png", bankUrl: "https://www.mbna.ca/en/credit-cards.html", perks: ["2% cashback on gas & groceries", "1% cashback on all other eligible purchases", "Rental Vehicle Collision Damage Waiver", "World Mastercard benefits", "$39/yr annual fee"] },
  { id: "mbna-amazon", name: "Amazon.ca Rewards Mastercard", issuer: "MBNA", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.015 }, badge: "🛒 Amazon Cashback", color: "#FF9900", description: "Prime: 2.5% at Amazon.ca & Whole Foods. Non-Prime: 1.5%. Always 1% everywhere else. No annual fee.", img: "/cards/amazon-mastercard.jpeg", bankUrl: "https://www.amazon.ca/credit-card", perks: ["Prime members: 2.5% at Amazon.ca & Whole Foods + 2.5% on foreign currency", "Non-Prime: 1.5% at Amazon.ca & Whole Foods + 1% on foreign currency", "Always 1% everywhere else Mastercard is accepted", "No annual fee", "Foreign currency cashback offsets FX fees"] },

  // ── PC FINANCIAL ──────────────────────────────────────────
  { id: "pc-world-elite", name: "PC World Elite Mastercard", issuer: "PC Financial", annualFee: 0, rates: { dining: 0.01, grocery: 0.03, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "🛒 PC Optimum", color: "#CC0000", description: "3% back at Loblaws grocery, 4.5% at Shoppers, 3¢/L at Esso & Mobil. 1% on dining, transit & else.", img: "/cards/pc-world-elite.webp", bankUrl: "https://www.pcfinancial.ca/en/credit-cards/", perks: ["3% back in PC Optimum points at Loblaws-banner grocery stores", "4.5% back at Shoppers Drug Mart & Pharmaprix", "At least 3¢/L back at Esso & Mobil stations", "3% back at Joe Fresh", "1% on dining, transit & everywhere else · No annual fee"] },
  { id: "pc-insiders", name: "PC Insiders World Elite Mastercard", issuer: "PC Financial", annualFee: 120, rates: { dining: 0.01, grocery: 0.04, gas: 0.045, travel: 0.01, other: 0.01 }, badge: "🛒 PC Insiders", color: "#CC0000", description: "4% at Loblaws grocery (+2% pickup), up to 7¢/L at Esso & Mobil, 5% at Shoppers. 1% on dining & else.", img: "/cards/pc-insiders.png", bankUrl: "https://www.pcfinancial.ca/en/credit-cards/", perks: ["4% back at Loblaws-banner grocery stores (+2% on eligible pickup orders)", "Up to 7¢/L back at Esso & Mobil stations", "5% back at Shoppers Drug Mart & Pharmaprix", "4% back at Joe Fresh", "1% on dining, transit & everywhere else · $120/yr annual fee"] },
  { id: "pc-world", name: "PC World Mastercard", issuer: "PC Financial", annualFee: 0, rates: { dining: 0.01, grocery: 0.02, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "🛒 PC Optimum", color: "#CC0000", description: "2% back at Loblaws grocery, 3.5% at Shoppers, 3¢/L at Esso & Mobil. 1% on dining, transit & else.", img: "/cards/pc-world.webp", bankUrl: "https://www.pcfinancial.ca/en/credit-cards/", perks: ["2% back in PC Optimum points at Loblaws-banner grocery stores", "3.5% back at Shoppers Drug Mart & Pharmaprix", "At least 3¢/L back at Esso & Mobil stations", "2% back at Joe Fresh", "1% on dining, transit & everywhere else · No annual fee"] },
  { id: "pc-mastercard", name: "PC Mastercard", issuer: "PC Financial", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.02, travel: 0.01, other: 0.01 }, badge: "🛒 Entry PC Card", color: "#CC0000", description: "1% back at Loblaws grocery, 2.5% at Shoppers, 3¢/L at Esso & Mobil. 1% on dining, transit & else.", img: "/cards/pc-mastercard.webp", bankUrl: "https://www.pcfinancial.ca/en/credit-cards/", perks: ["1% back in PC Optimum points at Loblaws-banner grocery stores", "2.5% back at Shoppers Drug Mart & Pharmaprix", "At least 3¢/L back at Esso & Mobil stations", "1% back at Joe Fresh", "1% on dining, transit & everywhere else · No annual fee"] },

  // ── BRIM FINANCIAL ────────────────────────────────────────
  { id: "brim-world-elite", name: "Brim World Elite Mastercard", issuer: "Brim Financial", annualFee: 89, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "💳 Brim Rewards", color: "#1A1A2E", description: "1 Brim point per $1 on all purchases. Premium World Elite benefits.", img: "/cards/brim.png", bankUrl: "https://www.brimfinancial.com/", perks: ["1 Brim point per $1 on all purchases", "World Elite Mastercard benefits", "Instalment plans", "Modern app experience", "$89/yr annual fee"] },
  { id: "brim", name: "Brim Mastercard", issuer: "Brim Financial", annualFee: 0, rates: { dining: 0.005, grocery: 0.005, gas: 0.005, travel: 0.005, other: 0.005 }, badge: "🆓 No-Fee Brim", color: "#1A1A2E", description: "1 Brim point per $2 on all purchases. No annual fee. 1.5% foreign transaction fee.", img: "/cards/brim.png", bankUrl: "https://www.brimfinancial.com/", perks: ["1 Brim point per $2 on all purchases", "No annual fee", "1.5% foreign transaction fee", "Easy instalment plans", "Modern app experience"] },

  // ── ROGERS / FIDO ─────────────────────────────────────────
  { id: "rogers-world-elite", name: "Rogers Red World Elite Mastercard", issuer: "Rogers Bank", annualFee: 0, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.02, other: 0.02 }, badge: "📱 2% Cashback", color: "#DA291C", description: "2% cashback on all purchases (with a Rogers/Fido/Shaw service), 3% on USD. Effectively 3% redeemed on Rogers bills. No fee.", img: "/cards/rogers-world-elite.png", bankUrl: "https://www.rogersbank.com/en/rogers_world_elite_mastercard", perks: ["2% cashback on all eligible purchases (with a qualifying Rogers, Fido, Shaw or Comwave service)", "1.5% cashback without a qualifying service", "3% cashback on US-dollar purchases", "1.5x redemption bonus = effective 3% when applied to Rogers/Fido bills or hardware", "5 free Roam Like Home days/yr (up to $90 value) · No annual fee"] },
  { id: "rogers-red", name: "Rogers Red Mastercard", issuer: "Rogers Bank", annualFee: 0, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.02, other: 0.02 }, badge: "📱 2% Cashback", color: "#DA291C", description: "2% cashback on all purchases with a Rogers/Fido/Shaw service (1% without). 2% on US-dollar purchases. No fee.", img: "/cards/rogers-red.png", bankUrl: "https://www.rogersbank.com/en/rogers_red_mastercard", perks: ["2% cashback on all eligible purchases (with a qualifying Rogers, Fido, Shaw or Comwave service)", "1% cashback without a qualifying service", "2% cashback on US-dollar purchases", "Redeem against Rogers/Fido bills or at checkout", "No annual fee"] },

  // ── CANADIAN TIRE ─────────────────────────────────────────
  { id: "triangle-world-elite", name: "Triangle World Elite Mastercard", issuer: "Canadian Tire", annualFee: 0, rates: { dining: 0.01, grocery: 0.03, gas: 0.03, travel: 0.01, other: 0.01 }, badge: "🍁 CT Money", color: "#E3141B", description: "4% CT Money at Canadian Tire stores, 5-7¢/L at Gas+ & Petro-Canada, 3% at groceries. 1% else.", img: "/cards/canadian_tire_world_elite_mastercard.webp", bankUrl: "https://www.canadiantire.ca/en/credit-services/triangle-world-elite-mastercard.html", perks: ["4% CT Money at Canadian Tire, Sport Chek, Mark's, Atmosphere & partner stores", "7¢/L on premium fuel, 5¢/L on other fuel at Gas+ & Petro-Canada", "3% CT Money at grocery stores (first $12k/yr; excl Costco & Walmart)", "1% CT Money everywhere else · Redeem $1 for $1", "No annual fee · Weekly personalized offers up to 25x"] },
  { id: "triangle", name: "Triangle Mastercard", issuer: "Canadian Tire", annualFee: 0, rates: { dining: 0.005, grocery: 0.015, gas: 0.03, travel: 0.005, other: 0.005 }, badge: "🍁 CT Money", color: "#E3141B", description: "4% CT Money at Canadian Tire family stores, 5¢/L at Gas+ & Petro-Canada, 1.5% at groceries. 0.5% else.", img: "/cards/canadian_tire_spot-triangle-mastercard.webp", bankUrl: "https://www.canadiantire.ca/en/credit-services/triangle-mastercard.html", perks: ["4% CT Money at Canadian Tire, Sport Chek, Mark's, Atmosphere & partner stores", "5¢/L CT Money at Gas+ & Petro-Canada fuel", "1.5% CT Money at grocery stores (first $12k/yr; excl Costco & Walmart)", "0.5% CT Money everywhere else · Redeem $1 for $1", "No annual fee · Weekly personalized offers up to 25x"] },

  // ── TANGERINE ─────────────────────────────────────────────
  { id: "tangerine-world", name: "Tangerine Money-Back World Mastercard", issuer: "Tangerine", annualFee: 0, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.005, other: 0.005 }, badge: "💸 Choose Your 2%", color: "#FF6600", description: "2% unlimited cashback in up to 3 categories you choose. 0.5% on everything else. World Mastercard benefits. No fee.", img: "/cards/tangerine-world.png", bankUrl: "https://www.tangerine.ca/en/products/spending/creditcard", perks: ["2% unlimited cashback in 2 categories of your choice", "Unlock a 3rd 2% category by depositing cashback into a Tangerine Savings Account", "0.5% cashback on everything else", "World Mastercard benefits (mobile device insurance, rental car coverage)", "No annual fee · Estimate assumes grocery, dining & gas as your picks"] },
  { id: "tangerine-rewards-world-elite", name: "Tangerine Rewards World Elite Mastercard", issuer: "Tangerine", annualFee: 120, rates: { dining: 0.015, grocery: 0.015, gas: 0.015, travel: 0.01, other: 0.01 }, badge: "🎬 Scene+ Boost", color: "#FF6600", description: "1.5x Scene+ on 3 chosen Accelerator categories (switch every 90 days). 1x else. Up to 10¢/L at Shell.", img: "", bankUrl: "https://www.tangerine.ca/en/products/spending/creditcard", perks: ["1.5x Scene+ points on 3 chosen Accelerator categories (switchable every 90 days)", "1x Scene+ point per $1 on everything else", "Up to 10¢/L in value on fuel at participating Shell stations", "Airport lounge passes & travel insurances", "$120/yr annual fee · Estimate assumes grocery, dining & gas as your picks"] },
  { id: "tangerine-money-back", name: "Tangerine Money-Back Credit Card", issuer: "Tangerine", annualFee: 0, rates: { dining: 0.02, grocery: 0.02, gas: 0.02, travel: 0.005, other: 0.005 }, badge: "💸 Choose Your 2%", color: "#FF6600", description: "2% unlimited cashback in up to 3 categories you choose. 0.5% on everything else. No annual fee.", img: "/cards/tangerine-money-back.jpg", bankUrl: "https://www.tangerine.ca/en/products/spending/creditcard", perks: ["2% unlimited cashback in 2 categories of your choice", "Unlock a 3rd 2% category by depositing cashback into a Tangerine Savings Account", "0.5% cashback on everything else", "No annual fee · No cashback limit", "Estimate assumes grocery, dining & gas as your picks"] },

  // ── SIMPLII FINANCIAL ─────────────────────────────────────
  { id: "simplii-cashback", name: "Simplii Financial Cash Back Visa", issuer: "Simplii Financial", annualFee: 0, rates: { dining: 0.04, grocery: 0.015, gas: 0.015, travel: 0.005, other: 0.005 }, badge: "🍽️ 4% Dining", color: "#CC0000", description: "4% on restaurants, bars & coffee shops. 1.5% on gas, groceries, drugstore & bills. 0.5% else. No fee.", img: "/cards/simplii.webp", bankUrl: "https://www.simplii.com/en/credit-cards.html", perks: ["4% cashback on restaurants, bars & coffee shops (up to $5k/yr)", "1.5% on gas, groceries, drugstore & pre-authorized payments (up to $15k/yr)", "0.5% on all other purchases (no limit)", "No annual fee", "Monthly cashback deposit"] },



  // ── ATB FINANCIAL ─────────────────────────────────────────
  { id: "atb-world-elite", name: "ATB World Elite Mastercard", issuer: "ATB Financial", annualFee: 120, rates: { dining: 0.015, grocery: 0.015, gas: 0.015, travel: 0.015, other: 0.015 }, badge: "🌾 Alberta Card", color: "#004B8D", description: "1.5% cashback everywhere. Great for Albertans who bank with ATB.", img: "", bankUrl: "https://www.atb.com/personal/bank/credit-cards/", perks: ["1.5% cashback on all purchases", "World Elite Mastercard benefits", "Travel insurance", "Alberta-focused banking", "$120/yr annual fee"] },
  { id: "atb-mastercard", name: "ATB Mastercard", issuer: "ATB Financial", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.005, other: 0.005 }, badge: "🌾 ATB Starter", color: "#004B8D", description: "No fee ATB Mastercard. Good for ATB banking customers.", img: "/cards/atb_gold_mastercard.png", bankUrl: "https://www.atb.com/personal/bank/credit-cards/", perks: ["ATB Rewards on purchases", "No annual fee", "ATB banking integration", "Fraud protection", "Alberta banking community"] },

  // ── NEO FINANCIAL ─────────────────────────────────────────
  { id: "neo-world-elite", name: "Neo World Mastercard", issuer: "Neo Financial", annualFee: 0, rates: { dining: 0.005, grocery: 0.02, gas: 0.02, travel: 0.005, other: 0.005 }, badge: "🚀 Fintech Cashback", color: "#7B2D8B", description: "2% on groceries, gas & recurring payments. 0.5% on everything else. Variable partner cashback. No fee.", img: "/cards/neo_world_elite_mastercard.avif", bankUrl: "https://www.neofinancial.com/credit-card", perks: ["2% cashback on groceries", "2% cashback on gas", "2% cashback on recurring payments", "0.5% on everything else · Variable cashback at Neo partners", "No annual fee · Modern banking app"] },
  { id: "neo-world-elite-mc", name: "Neo World Elite Mastercard", issuer: "Neo Financial", annualFee: 125, rates: { dining: 0.01, grocery: 0.05, gas: 0.03, travel: 0.01, other: 0.01 }, badge: "🚀 Premium Cashback", color: "#7B2D8B", description: "5% on groceries, 3% on gas, 4% on recurring payments. 1% on everything else. Variable partner cashback.", img: "/cards/neo-world-elite.jpeg", bankUrl: "https://www.neofinancial.com/credit-card", perks: ["5% cashback on groceries", "3% cashback on gas", "4% cashback on recurring payments", "1% on everything else · Variable cashback at Neo partners", "$125/yr annual fee"] },
  { id: "neo-mastercard", name: "Neo Mastercard", issuer: "Neo Financial", annualFee: 0, rates: { dining: 0.005, grocery: 0.01, gas: 0.01, travel: 0.005, other: 0.005 }, badge: "🚀 No-Fee Fintech", color: "#7B2D8B", description: "1% cashback on groceries & gas. Variable cashback at Neo partner merchants. No annual fee.", img: "/cards/noe_world_mastercard.avif", bankUrl: "https://www.neofinancial.com/credit-card", perks: ["1% cashback on groceries", "1% cashback on gas", "Average 5% cashback at Neo partner merchants (varies)", "Guaranteed minimum 0.5% cashback", "No annual fee · Modern banking app"] },

  // ── CAPITAL ONE ───────────────────────────────────────────
  { id: "capital-one-guaranteed", name: "Capital One Guaranteed Mastercard", issuer: "Capital One", annualFee: 0, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "🌱 Credit Builder", color: "#004A97", description: "Guaranteed approval credit-building card. No rewards or cashback. No annual fee.", img: "/cards/capital_one_guaranteed_mastercard.png", bankUrl: "https://www.capitalone.ca/", perks: ["Guaranteed approval", "Build or rebuild your credit", "No rewards or cashback", "No annual fee", "Reports to credit bureaus"] },
  { id: "capital-one-secured", name: "Capital One Guaranteed Secured Mastercard", issuer: "Capital One", annualFee: 0, rates: { dining: 0, grocery: 0, gas: 0, travel: 0, other: 0 }, badge: "🔒 Secured Builder", color: "#004A97", description: "Secured credit-building card with a refundable deposit. No rewards. No annual fee.", img: "/cards/capital_one_secured-mastercard-card-art-8fe01f8a08e10e7f06a563278eed22ca.png", bankUrl: "https://www.capitalone.ca/", perks: ["Guaranteed approval with a security deposit", "Build or rebuild your credit", "No rewards or cashback", "No annual fee", "Reports to credit bureaus"] },
  { id: "capital-one-smart-rewards", name: "Capital One Smart Rewards Mastercard", issuer: "Capital One", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "💳 Pay-to-Earn", color: "#004A97", description: "Earn 5 points per $1 paid toward your balance (~1% effective). No annual fee.", img: "/cards/CAPITAL_ONE_SMART_REWARDS_MASTERCARD.png", bankUrl: "https://www.capitalone.ca/", perks: ["5 points per $1 paid toward your balance", "Rewards earned on payments, not purchases", "~1% effective return when you pay off your spending", "No annual fee", "Redeem points for rewards"] },
  { id: "capital-one-aspire-cash", name: "Capital One Aspire Cash Platinum Mastercard", issuer: "Capital One", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "💵 1% Cashback", color: "#004A97", description: "1% cash rewards on every $1 spent. No annual fee.", img: "/cards/capital-one-aspire-cash.png", bankUrl: "https://www.capitalone.ca/", perks: ["1% cash rewards on all purchases", "No annual fee", "No cap on cash rewards", "Purchase protections", "Simple flat-rate cashback"] },
  { id: "capital-one-aspire", name: "Capital One Aspire Travel Platinum Mastercard", issuer: "Capital One", annualFee: 0, rates: { dining: 0.01, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "✈️ Reward Miles", color: "#004A97", description: "1 Reward mile per $1 on all purchases (~1% in travel value). No annual fee.", img: "/cards/Capital_one_aspire-travel-card-art.png", bankUrl: "https://www.capitalone.ca/", perks: ["1 Reward mile per $1 on all purchases", "Redeem miles for travel (100 miles = $1)", "No annual fee", "Travel & purchase protections", "Flexible travel redemptions"] },



  // ── ADDITIONAL ────────────────────────────────────────────
  { id: "scotiabank-student", name: "Scotiabank Scene+ Student Visa", issuer: "Scotiabank", annualFee: 0, rates: { dining: 0.02, grocery: 0.01, gas: 0.01, travel: 0.01, other: 0.01 }, badge: "🎓 Student Scene+", color: "#CC0000", description: "Scene+ points with no annual fee for students. Great movie rewards.", img: "/cards/scotia_no_fee_visa.webp", bankUrl: "https://www.scotiabank.com/ca/en/personal/credit-cards/student.html", perks: ["2x Scene+ Points on dining & entertainment", "1x Scene+ Point on all other purchases", "Redeem for movies, travel, food & more", "No annual fee · No minimum income required", "Access to Scene+ rewards program"] },
  { id: "cibc-student", name: "CIBC Dividend Visa for Students", issuer: "CIBC", annualFee: 0, rates: { dining: 0.01, grocery: 0.02, gas: 0.01, travel: 0.01, other: 0.005 }, badge: "🎓 Student Cashback", color: "#C41230", description: "2% cashback on groceries. 1% on gas, EV, transport, dining, bills & travel. 0.5% else. For students.", img: "/cards/cibc_dividend_for_students.avif", bankUrl: "https://www.cibc.com/en/personal-banking/credit-cards/student.html", perks: ["2% cashback on groceries", "1% on gas, EV charging, transportation, dining, recurring payments & travel via CIBC by Expedia", "0.5% cashback on everything else", "No annual fee · No minimum income required", "Build credit as a student"] },
];


export const STEPS: Step[] = [
  {
    key: "dining",
    icon: "🍽️",
    label: "Dining & Restaurants",
    question: "How much do you spend eating out each month?",
    hint: "Restaurants, cafes, takeout, food delivery",
    max: 2000,
    defaultVal: 400,
    presets: [
      { label: "Light ($200)", value: 200 },
      { label: "Average ($400)", value: 400 },
      { label: "Frequent ($800)", value: 800 },
      { label: "Daily ($1,500)", value: 1500 },
    ],
  },
  {
    key: "grocery",
    icon: "🛒",
    label: "Groceries",
    question: "What's your monthly grocery budget?",
    hint: "Supermarkets, Costco, farm boxes",
    max: 3000,
    defaultVal: 600,
    presets: [
      { label: "Solo ($300)", value: 300 },
      { label: "Couple ($600)", value: 600 },
      { label: "Family ($1,000)", value: 1000 },
      { label: "Large family ($1,800)", value: 1800 },
    ],
  },
  {
    key: "gas",
    icon: "⛽",
    label: "Gas & Fuel",
    question: "How much do you spend on gas monthly?",
    hint: "Petrol, diesel, EV charging",
    max: 1500,
    defaultVal: 150,
    presets: [
      { label: "Minimal ($50)", value: 50 },
      { label: "Commuter ($150)", value: 150 },
      { label: "Heavy driver ($300)", value: 300 },
      { label: "Fleet ($600)", value: 600 },
    ],
  },
  {
    key: "travel",
    icon: "✈️",
    label: "Travel",
    question: "What do you spend monthly on travel?",
    hint: "Flights, hotels, car rentals (annual total ÷ 12)",
    max: 5000,
    defaultVal: 300,
    presets: [
      { label: "Occasional ($100)", value: 100 },
      { label: "A few trips ($300)", value: 300 },
      { label: "Frequent ($700)", value: 700 },
      { label: "Road warrior ($2,000)", value: 2000 },
    ],
  },
  {
    key: "other",
    icon: "🛍️",
    label: "Shopping & Other",
    question: "Everything else — what's left?",
    hint: "Shopping, utilities, subscriptions, services",
    max: 5000,
    defaultVal: 500,
    presets: [
      { label: "Minimal ($200)", value: 200 },
      { label: "Average ($500)", value: 500 },
      { label: "Active ($1,000)", value: 1000 },
      { label: "Heavy ($2,500)", value: 2500 },
    ],
  },
];

export function fmt(n: number) {
  return "$" + Math.round(n).toLocaleString("en-CA");
}

export function fmtRate(r: number): string {
  return parseFloat((r * 100).toFixed(2)) + "%";
}

export function getBreakdown(card: CardDef, spend: Record<SpendKey, number>) {
  const rows = STEPS.map((s) => ({
    key: s.key,
    label: CAT_LABELS[s.key],
    rate: card.rates[s.key],
    annual: spend[s.key] * 12 * card.rates[s.key],
  }));
  const gross = rows.reduce((sum, r) => sum + r.annual, 0);
  return { rows, gross };
}

export function scoreCard(card: CardDef, spend: Record<SpendKey, number>): number {
  const annualEarn = Object.entries(spend).reduce(
    (sum, [k, v]) => sum + v * 12 * card.rates[k as SpendKey],
    0
  );
  return annualEarn - card.annualFee;
}

export function getTopCards(spend: Record<SpendKey, number>, n = 3) {
  return [...CARDS]
    .map((c) => ({ ...c, netValue: scoreCard(c, spend) }))
    .sort((a, b) => b.netValue - a.netValue)
    .slice(0, n);
}
