/**
 * Regenerate src/app/fonts.css and public/fonts/* from Next's own
 * next/font/google output.
 *
 * Only needed if the font families, weights or styles ever change. To use it:
 *   1. temporarily restore the next/font/google imports in src/app/layout.tsx
 *   2. npm run build
 *   3. node scripts/extract-fonts.mjs
 *   4. remove the next/font/google imports again
 *
 * This exists so the build never has to reach Google Fonts, which was
 * intermittently failing `next build` with "Error while requesting resource".
 */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

const cssFile = execSync(
  `grep -rl "@font-face" .next --include="*.css" | grep -v "/dev/" | head -1`
).toString().trim();
const css = fs.readFileSync(cssFile, "utf8");
const faces = css.match(/@font-face\s*\{[^}]*\}/g) ?? [];
if (faces.length === 0) throw new Error("no @font-face rules found — did you build with next/font/google restored?");

fs.mkdirSync("public/fonts", { recursive: true });
const files = new Set();
for (const f of faces) {
  for (const u of f.match(/url\(\.\.\/media\/([^)]+\.woff2)\)/g) ?? []) {
    files.add(u.match(/media\/([^)]+\.woff2)/)[1]);
  }
}
for (const f of files) fs.copyFileSync(path.join(".next/static/media", f), path.join("public/fonts", f));

const rewritten = faces.map((f) => f.replace(/url\(\.\.\/media\//g, "url(/fonts/"));
fs.writeFileSync(
  "src/app/fonts.css",
  `/* Self-hosted fonts — generated by scripts/extract-fonts.mjs. Do not edit by hand. */\n\n${rewritten.join("\n\n")}\n\n:root {\n  --font-archivo: "Archivo", "Archivo Fallback";\n  --font-fraunces: "Fraunces", "Fraunces Fallback";\n  --font-jetbrains: "JetBrains Mono", "JetBrains Mono Fallback";\n}\n`
);
console.log(`fonts: ${files.size} files, ${rewritten.length} @font-face rules`);
